version: "3"
services:
  hypernode:
    container_name: hypernode
    image: docker.hypernode.com/byteinternet/hypernode-buster-docker-php81-mysql57
    volumes:
      - ./ci/test/.ssh:/root/.ssh
    ports:
      - "2222:22"
