version: '3.9'
services:
  hypernode:
    container_name: hypernode
    image: docker.hypernode.com/byteinternet/hypernode-buster-docker-php81-mysql57
    volumes:
      - ./ci/test/.ssh:/root/.ssh
      - ${MAGENTO_REPO:-../magento2.komkommer.store}:/banaan
  deploy:
    build:
      context: .
      dockerfile: ci/build/Dockerfile
      # Match environment of magento2.komkommer.store
      args:
      - NODE_VERSION=16
      - PHP_VERSION=8.1
    command: "/bin/bash -c 'sleep 5000'"
    working_dir: /web
    volumes:
      - ./ci/test/.ssh:/root/.ssh
      - ./ci/test/magento/deploy.php:/deploy_simple.php
    depends_on:
    - hypernode
