version: "3"
services:
  hypernode:
    container_name: hypernode
    image: docker.hypernode.com/byteinternet/hypernode-bookworm-docker-php${PHP_VERSION_SHORT:-81}-mysql80
    volumes:
      - ./ci/test/.ssh:/root/.ssh
    ports:
      - "2222:22"
  deploy:
    build:
      context: .
      dockerfile: ci/build/Dockerfile
      # Match environment of magento2.komkommer.store
      args:
      - NODE_VERSION=16
      - PHP_VERSION=${PHP_VERSION:-8.1}
    command: "/bin/bash -c 'sleep 5000'"
    working_dir: /web
    volumes:
      - ./ci/test/.ssh:/root/.ssh
      - ./ci/test/magento:/config
