.variables-php7-2:
    variables:
        PHP_VERSION: "7.2"

.variables-php7-3:
    variables:
        PHP_VERSION: "7.3"

.variables-php7-4:
    variables:
        PHP_VERSION: "7.4"

.variables-php8-0:
    variables:
        PHP_VERSION: "8.0"
