name: Test
on:
    pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout hypernode-deploy
      uses: actions/checkout@v3
    - name: Checkout magento2.komkommer.store
      uses: actions/checkout@v3
      with:
        repository: ByteInternet/magento2.komkommer.store
        path: "./magento2.komkommer.store"
        token: "${{secrets.HYPERNODE_PULL_REPO_TOKEN}}"
    - name: Run test script
      run: MAGENTO_REPO=./magento2.komkommer.store ./runtests.sh
      shell: bash
