name: Run tests for PR
on:
  pull_request:

jobs:
  integration_test:
    strategy:
      matrix:
        php_version: [8.1, 8.2, 8.3]
        testsuite: [general]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hypernode-deploy
        uses: actions/checkout@v3
      - name: Run general testsuite
        if: ${{ matrix.testsuite == 'general' }}
        run: MAGENTO_REPO=./magento2 ./runtests.sh general
        shell: bash
        env:
          PHP_VERSION: ${{ matrix.php_version }}
      - name: Start SSH agent for brancher testsuite
        if: ${{ matrix.testsuite == 'brancher' && matrix.php_version == '8.3' }}
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run brancher testsuite
        if: ${{ matrix.testsuite == 'brancher' && matrix.php_version == '8.3' }}
        run: ./runtests.sh brancher
        shell: bash
        env:
          PHP_VERSION: ${{ matrix.php_version }}
          HYPERNODE_API_TOKEN: ${{ secrets.HYPERNODE_API_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  code_quality:
    strategy:
      matrix:
        php_version: [7.4, 8.1, 8.2, 8.3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hypernode-deploy
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          tools: composer:v2
      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest
      - name: Run the code quality tests
        run: php vendor/bin/grumphp run --no-interaction
